DENOPTIM: denoptim.ga.EAUtilsTest Class Reference
denoptim.ga.EAUtilsTest Class Reference
Unit test.
Public Member Functions
void testBuildGraphFromTemplateScaffold () throws Exception
void testAvoidRedundantXOver () throws Exception
void testBuildByXOver_SubGraph () throws Exception
void testBuildByXOver_Embedded_Free () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
void testBuildByXOver_Embedded_FreeBackwards () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
void testBuildByXOver_Embedded_FixedStructure () throws Exception
void testCandidateGenerationMethod () throws Exception
void testCandidateGenerationMethodReproducibility () throws Exception
void testCrowdingProbability () throws Exception
void testSelectNonScaffoldNonCapVertex () throws Exception
void testChooseNumberOfSitesToMutate () throws Exception
Private Member Functions
FragmentSpaceParameters prepare () throws DENOPTIMException
Static Private Attributes
static APClass APCA
static APClass APCB
static APClass APCC
static String a ="A"
static String b ="B"
static String c ="C"
Detailed Description
Unit test.
Author
Marco Foscato
Definition at line 57 of file EAUtilsTest.java.
Member Function Documentation
prepare()
FragmentSpaceParameters denoptim.ga.EAUtilsTest.prepare () throws DENOPTIMException private
Definition at line 65 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.a, denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addRing(), denoptim.graph.DGraph.addVertex(), denoptim.ga.EAUtilsTest.APCA, denoptim.ga.EAUtilsTest.APCB, denoptim.ga.EAUtilsTest.APCC, denoptim.graph.DGraph.appendVertexOnAP(), denoptim.fragspace.FragmentSpace.appendVertexToLibrary(), denoptim.ga.EAUtilsTest.b, denoptim.ga.EAUtilsTest.c, denoptim.graph.Template.ContractLevel.FIXED_STRUCT, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.fragspace.FragmentSpace.getFragmentLibrary(), denoptim.fragspace.FragmentSpace.getScaffoldLibrary(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.APClass.make(), denoptim.graph.Vertex.newVertexFromLibrary(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.fragspace.FragmentSpace.setAPclassBasedApproach(), denoptim.graph.Vertex.setAsRCV(), denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.graph.Edge.BondType.SINGLE.
Referenced by denoptim.ga.EAUtilsTest.testAvoidRedundantXOver(), and denoptim.ga.EAUtilsTest.testBuildGraphFromTemplateScaffold().
testAvoidRedundantXOver()
void denoptim.ga.EAUtilsTest.testAvoidRedundantXOver () throws Exception
Definition at line 189 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.DGraph.clone(), denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.ga.EAUtilsTest.prepare(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.graph.Vertex.setBuildingBlockType(), and denoptim.programs.RunTimeParameters.setParameters().
testBuildByXOver_Embedded_FixedStructure()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FixedStructure () throws Exception
Definition at line 415 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FIXED_STRUCT, denoptim.graph.Candidate.getGraph(), denoptim.graph.Template.getInnerGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.graph.DGraph.getVertexList(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.Template.setContractLevel().
testBuildByXOver_Embedded_Free()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_Free () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
Note that the order of APs in on the templates changes as a result of the crossover. For this reason, the backwards crossover of the graphs from getPairOfTestGraphsBxo() does not produce the graphs from getPairOfTestGraphsB(), but those from getPairOfTestGraphsBxoxo().
Definition at line 307 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FREE, denoptim.graph.Candidate.getGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsB(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.DGraph.sameAs().
testBuildByXOver_Embedded_FreeBackwards()
void denoptim.ga.EAUtilsTest.testBuildByXOver_Embedded_FreeBackwards () throws Exception
NB: the graphs from methods getPairOfTestGraphsB() and getPairOfTestGraphsBxo() and
getPairOfTestGraphsBxoxo() are a sequence resulting from crossover operations.
Note that the order of APs in on the templates changes as a result of the crossover. For this reason, the backwards crossover of the graphs from getPairOfTestGraphsBxo() does not produce the graphs from getPairOfTestGraphsB(), but those from getPairOfTestGraphsBxoxo().
Definition at line 366 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.Template.ContractLevel.FREE, denoptim.graph.Candidate.getGraph(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxo(), denoptim.ga.PopulationTest.getPairOfTestGraphsBxoxo(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.DGraph.sameAs().
testBuildByXOver_SubGraph()
void denoptim.ga.EAUtilsTest.testBuildByXOver_SubGraph () throws Exception
Definition at line 230 of file EAUtilsTest.java.
References denoptim.ga.Population.add(), denoptim.ga.EAUtils.buildCandidateByXOver(), denoptim.graph.DGraph.getChildrenTree(), denoptim.graph.DGraph.getEdgeCount(), denoptim.graph.Candidate.getGraph(), denoptim.graph.DGraph.getVertexCount(), denoptim.graph.DGraph.getVertexList(), denoptim.ga.PopulationTest.makeGraphA(), denoptim.ga.PopulationTest.makeGraphE(), denoptim.ga.PopulationTest.prepare(), and denoptim.graph.Candidate.setFitness().
testBuildGraphFromTemplateScaffold()
void denoptim.ga.EAUtilsTest.testBuildGraphFromTemplateScaffold () throws Exception
Definition at line 159 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.buildGraph(), denoptim.graph.Template.getMutationSites(), denoptim.graph.DGraph.getVertexAtPosition(), denoptim.ga.EAUtilsTest.prepare(), and denoptim.programs.RunTimeParameters.setParameters().
testCandidateGenerationMethod()
void denoptim.ga.EAUtilsTest.testCandidateGenerationMethod () throws Exception
Definition at line 524 of file EAUtilsTest.java.
References denoptim.ga.EAUtilsTest.c, and denoptim.ga.EAUtils.pickNewCandidateGenerationMode().
testCandidateGenerationMethodReproducibility()
void denoptim.ga.EAUtilsTest.testCandidateGenerationMethodReproducibility () throws Exception
Definition at line 564 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.pickNewCandidateGenerationMode().
testChooseNumberOfSitesToMutate()
void denoptim.ga.EAUtilsTest.testChooseNumberOfSitesToMutate () throws Exception
Definition at line 690 of file EAUtilsTest.java.
References denoptim.ga.EAUtils.chooseNumberOfSitesToMutate().
testCrowdingProbability()
void denoptim.ga.EAUtilsTest.testCrowdingProbability () throws Exception
Definition at line 613 of file EAUtilsTest.java.
References denoptim.graph.Vertex.getAP(), denoptim.graph.DGraph.getAttachmentPoints(), denoptim.ga.EAUtils.getCrowdingProbability(), denoptim.graph.DGraph.getVertexAtPosition(), and denoptim.graph.DGraphTest.makeTestGraphA().
testSelectNonScaffoldNonCapVertex()
void denoptim.ga.EAUtilsTest.testSelectNonScaffoldNonCapVertex () throws Exception
Definition at line 640 of file EAUtilsTest.java.
References denoptim.graph.EmptyVertex.addAP(), denoptim.graph.DGraph.addVertex(), denoptim.graph.DGraph.appendVertexOnAP(), denoptim.graph.Vertex.BBType.CAP, denoptim.graph.Vertex.BBType.FRAGMENT, denoptim.graph.Vertex.getAP(), denoptim.graph.Vertex.BBType.SCAFFOLD, denoptim.ga.EAUtils.selectNonScaffoldNonCapVertex(), and denoptim.graph.Vertex.setBuildingBlockType().
Member Data Documentation
a
String denoptim.ga.EAUtilsTest.a ="A" static private
Definition at line 61 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
APCA
APClass denoptim.ga.EAUtilsTest.APCA static private
Definition at line 60 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
APCB
APClass denoptim.ga.EAUtilsTest.APCB static private
Definition at line 60 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
APCC
APClass denoptim.ga.EAUtilsTest.APCC static private
Definition at line 60 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
b
String denoptim.ga.EAUtilsTest.b ="B" static private
Definition at line 61 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare().
c
String denoptim.ga.EAUtilsTest.c ="C" static private
Definition at line 61 of file EAUtilsTest.java.
Referenced by denoptim.ga.EAUtilsTest.prepare(), and denoptim.ga.EAUtilsTest.testCandidateGenerationMethod().
The documentation for this class was generated from the following file:
/github/workspace/src/test/java/denoptim/ga/EAUtilsTest.java