DENOPTIM: denoptim.ga.SelectionHelper Class Reference
denoptim.ga.SelectionHelper Class Reference
Class that offers methods to performs fitness-driven selection of candidates.
Static Protected Member Functions
static Candidate[] performTournamentSelection (ArrayList< Candidate > population, int sz, RunTimeParameters settings)
Select p individuals at random.
static Candidate[] performRandomSelection (ArrayList< Candidate > population, int sz, RunTimeParameters settings)
Randomly select k individuals from the population.
static Candidate[] performSUS (ArrayList< Candidate > population, int sz, RunTimeParameters settings)
Stochastic Uniform Sampling Note: this implementation is based on the WATCHMAKER framework http://watchmaker.uncommons.org/.
static Candidate[] performRWS (ArrayList< Candidate > population, int sz, RunTimeParameters settings)
Roulette wheel selection is implemented as follows:
Detailed Description
Class that offers methods to performs fitness-driven selection of candidates.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 33 of file SelectionHelper.java.
Member Function Documentation
performRandomSelection()
static Candidate[] denoptim.ga.SelectionHelper.performRandomSelection (ArrayList< Candidate > population, int sz, RunTimeParameters settings) static protected
Randomly select k individuals from the population.
Parameters
population the ensemble of individuals to choose from.
sz number of individuals to select.
settings the program-specific settings.
Returns
list of indices of individuals in the population.
Definition at line 88 of file SelectionHelper.java.
References denoptim.programs.RunTimeParameters.getRandomizer(), and denoptim.utils.Randomizer.randomlyChooseOne().
Referenced by denoptim.ga.EAUtils.selectBasedOnFitness().
performRWS()
static Candidate[] denoptim.ga.SelectionHelper.performRWS (ArrayList< Candidate > population, int sz, RunTimeParameters settings) static protected
Roulette wheel selection is implemented as follows:
Sum the fitness of all the population members. TF (total fitness).
Generate a random number r, between 0 and TF.
Return the first population member whose fitness added to the preceding population members is greater than or equal to r. Note: this implementation is based on the WATCHMAKER framework http://watchmaker.uncommons.org/
Parameters
population the ensemble of individuals to choose from.
sz number of individuals to select.
settings the program-specific settings.
Returns
list of indices of individuals in the population.
Definition at line 166 of file SelectionHelper.java.
References denoptim.graph.Candidate.getFitness(), denoptim.programs.RunTimeParameters.getRandomizer(), and denoptim.utils.Randomizer.nextDouble().
Referenced by denoptim.ga.EAUtils.selectBasedOnFitness().
performSUS()
static Candidate[] denoptim.ga.SelectionHelper.performSUS (ArrayList< Candidate > population, int sz, RunTimeParameters settings) static protected
Stochastic Uniform Sampling Note: this implementation is based on the WATCHMAKER framework http://watchmaker.uncommons.org/.
Parameters
population the ensemble of individuals to choose from.
sz number of individuals to select.
settings the program-specific settings.
Returns
list of indices of individuals in the population.
Definition at line 109 of file SelectionHelper.java.
References denoptim.graph.Candidate.getFitness(), denoptim.programs.RunTimeParameters.getRandomizer(), and denoptim.utils.Randomizer.nextDouble().
Referenced by denoptim.ga.EAUtils.selectBasedOnFitness().
performTournamentSelection()
static Candidate[] denoptim.ga.SelectionHelper.performTournamentSelection (ArrayList< Candidate > population, int sz, RunTimeParameters settings) static protected
Select p individuals at random.
The individual with the highest fitness becomes the parent. Keeping the tournament size small results in a smaller selection pressure, thus increasing genetic diversity. Note: this implementation is based on the WATCHMAKER framework http://watchmaker.uncommons.org/
Parameters
population the ensemble of individuals to choose from
sz number of individuals to select
settings the program-specific settings.
Returns
list of selected individuals
Definition at line 51 of file SelectionHelper.java.
References denoptim.graph.Candidate.getFitness(), denoptim.programs.RunTimeParameters.getRandomizer(), denoptim.utils.Randomizer.nextBoolean(), and denoptim.utils.Randomizer.randomlyChooseOne().
Referenced by denoptim.ga.EAUtils.selectBasedOnFitness().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/ga/SelectionHelper.java