DENOPTIM: denoptim.task.ParallelAsynchronousTaskExecutor Class Reference
denoptim.task.ParallelAsynchronousTaskExecutor Class Reference abstract
Runs tasks parallel in asynchronous fashion.
Public Member Functions
ParallelAsynchronousTaskExecutor (int numberOfTasks, Logger logger)
Constructor.
void stopRun ()
Stops all subtasks and shutdown executor.
void run () throws DENOPTIMException, IOException
Run the parallelized task.
Protected Member Functions
boolean subtaskHasException ()
Looks for exceptions in the subtasks and, if any, store its reference locally to allow reporting it back from the main thread.
Throwable getExceptionFromSubTask ()
boolean allTasksCompleted ()
Check for completion of all subtasks.
void submitTask (Task task, String logFilePathname)
abstract void createAndSubmitTasks ()
Implementations of this method must call the submitTask(Task, String) method to actually send the task to the executor and eventually start it.
abstract boolean doPostFlightOperations ()
abstract boolean doPreFlightOperations ()
Protected Attributes
final List< Future< Object > > futures
Storage of references to the submitted subtasks as Future
final ArrayList< Task > submitted
Storage of references to the submitted subtasks.
Package Attributes
final ThreadPoolExecutor tpe
Asynchronous tasks manager.
Private Member Functions
void cleanup (ThreadPoolExecutor tpe, List< Future< Object > > futures, ArrayList< Task > submitted)
clean all reference to submitted tasks
Private Attributes
Throwable thrownByTask
If any, here we stores the exception returned by a subtask.
Logger logger
Logger.
Detailed Description
Runs tasks parallel in asynchronous fashion.
Author
Marco Foscato
Definition at line 44 of file ParallelAsynchronousTaskExecutor.java.
Constructor & Destructor Documentation
ParallelAsynchronousTaskExecutor()
denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor (int numberOfTasks, Logger logger)
Constructor.
Definition at line 78 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.futures, denoptim.task.ParallelAsynchronousTaskExecutor.logger, denoptim.task.ParallelAsynchronousTaskExecutor.run(), denoptim.task.ParallelAsynchronousTaskExecutor.submitted, and denoptim.task.ParallelAsynchronousTaskExecutor.tpe.
Member Function Documentation
allTasksCompleted()
boolean denoptim.task.ParallelAsynchronousTaskExecutor.allTasksCompleted () protected
Check for completion of all subtasks.
Returns
true if all subtasks are completed
Definition at line 192 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.submitted.
cleanup()
void denoptim.task.ParallelAsynchronousTaskExecutor.cleanup (ThreadPoolExecutor tpe, List< Future< Object > > futures, ArrayList< Task > submitted) private
clean all reference to submitted tasks
Definition at line 292 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.futures, denoptim.task.ParallelAsynchronousTaskExecutor.submitted, and denoptim.task.ParallelAsynchronousTaskExecutor.tpe.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), and denoptim.task.ParallelAsynchronousTaskExecutor.stopRun().
createAndSubmitTasks()
abstract void denoptim.task.ParallelAsynchronousTaskExecutor.createAndSubmitTasks () abstract protected
Implementations of this method must call the submitTask(Task, String) method to actually send the task to the executor and eventually start it.
Reimplemented in denoptim.fragmenter.ParallelConformerExtractionAlgorithm, and denoptim.fragmenter.ParallelFragmentationAlgorithm.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.run().
doPostFlightOperations()
abstract boolean denoptim.task.ParallelAsynchronousTaskExecutor.doPostFlightOperations () abstract protected
Reimplemented in denoptim.fragmenter.ParallelConformerExtractionAlgorithm, and denoptim.fragmenter.ParallelFragmentationAlgorithm.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.run().
doPreFlightOperations()
abstract boolean denoptim.task.ParallelAsynchronousTaskExecutor.doPreFlightOperations () abstract protected
Reimplemented in denoptim.fragmenter.ParallelConformerExtractionAlgorithm, and denoptim.fragmenter.ParallelFragmentationAlgorithm.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.run().
getExceptionFromSubTask()
Throwable denoptim.task.ParallelAsynchronousTaskExecutor.getExceptionFromSubTask () protected
Returns
the trace of the problem occurred in the first subtask that was detected to have a problem.
Definition at line 181 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.thrownByTask.
run()
void denoptim.task.ParallelAsynchronousTaskExecutor.run () throws DENOPTIMException, IOException
Run the parallelized task.
Definition at line 212 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.createAndSubmitTasks(), denoptim.task.ParallelAsynchronousTaskExecutor.doPostFlightOperations(), denoptim.task.ParallelAsynchronousTaskExecutor.doPreFlightOperations(), denoptim.constants.DENOPTIMConstants.EOL, denoptim.task.ParallelAsynchronousTaskExecutor.logger, and denoptim.task.ParallelAsynchronousTaskExecutor.tpe.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), and denoptim.programs.fragmenter.Fragmenter.runProgram().
stopRun()
void denoptim.task.ParallelAsynchronousTaskExecutor.stopRun ()
Stops all subtasks and shutdown executor.
Definition at line 147 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.futures, denoptim.task.ParallelAsynchronousTaskExecutor.submitted, and denoptim.task.ParallelAsynchronousTaskExecutor.tpe.
Referenced by denoptim.programs.fragmenter.Fragmenter.handleThrowable().
submitTask()
void denoptim.task.ParallelAsynchronousTaskExecutor.submitTask (Task task, String logFilePathname) protected
Definition at line 259 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.futures, denoptim.task.Task.getId(), denoptim.task.ParallelAsynchronousTaskExecutor.logger, denoptim.task.ParallelAsynchronousTaskExecutor.submitted, and denoptim.task.ParallelAsynchronousTaskExecutor.tpe.
Referenced by denoptim.fragmenter.ParallelConformerExtractionAlgorithm.createAndSubmitTasks(), and denoptim.fragmenter.ParallelFragmentationAlgorithm.createAndSubmitTasks().
subtaskHasException()
boolean denoptim.task.ParallelAsynchronousTaskExecutor.subtaskHasException () protected
Looks for exceptions in the subtasks and, if any, store its reference locally to allow reporting it back from the main thread.
Returns
true if any of the subtasks has thrown an exception
Definition at line 160 of file ParallelAsynchronousTaskExecutor.java.
References denoptim.task.ParallelAsynchronousTaskExecutor.submitted, and denoptim.task.ParallelAsynchronousTaskExecutor.thrownByTask.
Member Data Documentation
futures
final List<Future<Object> > denoptim.task.ParallelAsynchronousTaskExecutor.futures protected
Storage of references to the submitted subtasks as Future
Definition at line 49 of file ParallelAsynchronousTaskExecutor.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), denoptim.task.ParallelAsynchronousTaskExecutor.stopRun(), and denoptim.task.ParallelAsynchronousTaskExecutor.submitTask().
logger
Logger denoptim.task.ParallelAsynchronousTaskExecutor.logger private
Logger.
Definition at line 69 of file ParallelAsynchronousTaskExecutor.java.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), denoptim.task.ParallelAsynchronousTaskExecutor.run(), and denoptim.task.ParallelAsynchronousTaskExecutor.submitTask().
submitted
final ArrayList<Task> denoptim.task.ParallelAsynchronousTaskExecutor.submitted protected
Storage of references to the submitted subtasks.
Definition at line 54 of file ParallelAsynchronousTaskExecutor.java.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.allTasksCompleted(), denoptim.fragmenter.ParallelFragmentationAlgorithm.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.cleanup(), denoptim.fragmenter.ParallelConformerExtractionAlgorithm.doPostFlightOperations(), denoptim.fragmenter.ParallelFragmentationAlgorithm.doPostFlightOperations(), denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), denoptim.task.ParallelAsynchronousTaskExecutor.stopRun(), denoptim.task.ParallelAsynchronousTaskExecutor.submitTask(), and denoptim.task.ParallelAsynchronousTaskExecutor.subtaskHasException().
thrownByTask
Throwable denoptim.task.ParallelAsynchronousTaskExecutor.thrownByTask private
If any, here we stores the exception returned by a subtask.
Definition at line 64 of file ParallelAsynchronousTaskExecutor.java.
Referenced by denoptim.task.ParallelAsynchronousTaskExecutor.getExceptionFromSubTask(), and denoptim.task.ParallelAsynchronousTaskExecutor.subtaskHasException().
tpe
final ThreadPoolExecutor denoptim.task.ParallelAsynchronousTaskExecutor.tpe package
Asynchronous tasks manager.
Definition at line 59 of file ParallelAsynchronousTaskExecutor.java.
Referenced by denoptim.fragmenter.ParallelFragmentationAlgorithm.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.cleanup(), denoptim.task.ParallelAsynchronousTaskExecutor.ParallelAsynchronousTaskExecutor(), denoptim.task.ParallelAsynchronousTaskExecutor.run(), denoptim.task.ParallelAsynchronousTaskExecutor.stopRun(), and denoptim.task.ParallelAsynchronousTaskExecutor.submitTask().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/task/ParallelAsynchronousTaskExecutor.java