DENOPTIM: denoptim.graph.SymmetricSet Class Reference
denoptim.graph.SymmetricSet Class Reference
Class representing a list of IDs pointing to instances that are related by some conventional criterion that is referred as the "symmetry".
Public Member Functions
SymmetricSet ()
Constructor for an empty "set" (a list, actually).
SymmetricSet (ArrayList< Integer > symIds)
Constructor for a symmetric list of identifiers from the list itself.
ArrayList< Integer > getList ()
Return the list of symmetric identifiers.
int get (int i)
Return a specific identifier contained in this "set" (a list in reality).
boolean contains (Integer val)
Checks whether the given identifiers is contained in this set.
int indexOf (Integer vid)
void set (int index, Integer element)
void add (int id)
Adds an identifiers to this list.
void remove (Integer i)
Removes the given identifier from the list.
int size ()
Return the number of identifiers in this list.
SymmetricSet clone ()
Returns a deep-copy of this set.
String toString ()
Private Attributes
ArrayList< Integer > symIds
Detailed Description
Class representing a list of IDs pointing to instances that are related by some conventional criterion that is referred as the "symmetry".
Note that the actual criterion that defined a "symmetry" relation is not defined here. So, this list does not know what is the criterion that puts its entries in relation with each other. Moreover, the list does not know what the entries are, just their numerical identifier.
Author
Vishwesh Venkatraman
Marco Foscato
Definition at line 36 of file SymmetricSet.java.
Constructor & Destructor Documentation
SymmetricSet() [1/2]
denoptim.graph.SymmetricSet.SymmetricSet ()
Constructor for an empty "set" (a list, actually).
Definition at line 45 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.SymmetricSet.clone().
SymmetricSet() [2/2]
denoptim.graph.SymmetricSet.SymmetricSet (ArrayList< Integer > symIds)
Constructor for a symmetric list of identifiers from the list itself.
Parameters
symIds the list of identifiers.
Definition at line 56 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Member Function Documentation
add()
void denoptim.graph.SymmetricSet.add (int id)
Adds an identifiers to this list.
Parameters
id the identifiers to add.
Definition at line 116 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.graph.SymmetricSet.clone(), denoptim.graph.DGraph.convertSymmetricLabelsToSymmetricSets(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.removeSymmetryRedundance(), denoptim.graph.DGraphTest.testSameAs_DiffSymmSet(), and denoptim.graph.DGraphTest.testSameAs_SameSymmSet().
clone()
SymmetricSet denoptim.graph.SymmetricSet.clone ()
Returns a deep-copy of this set.
Returns
a deep-copy.
Definition at line 156 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.add(), denoptim.graph.SymmetricSet.symIds, and denoptim.graph.SymmetricSet.SymmetricSet().
Referenced by denoptim.graph.DGraphTest.testReplaceVertex().
contains()
boolean denoptim.graph.SymmetricSet.contains (Integer val)
Checks whether the given identifiers is contained in this set.
Parameters
val the identifiers to look for.
Returns
true if the identifiers is contained in this set.
Definition at line 91 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.removeSymmetryRedundance(), denoptim.graph.DGraph.sameAs(), and denoptim.graph.FragmentTest.testConversionToIAC().
get()
int denoptim.graph.SymmetricSet.get (int i)
Return a specific identifier contained in this "set" (a list in reality).
Parameters
i the desired entry number.
Returns
the identifier.
Definition at line 79 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.GraphOperations.extendGraph(), and denoptim.graph.DGraph.sameAs().
getList()
ArrayList< Integer > denoptim.graph.SymmetricSet.getList ()
Return the list of symmetric identifiers.
Returns
the list of symmetric identifiers .
Definition at line 67 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.graph.DGraph.appendGraphOnGraph(), denoptim.graph.DGraph.changeSignOfVertexID(), denoptim.ga.GraphOperations.deleteChain(), denoptim.ga.GraphOperations.deleteFragment(), denoptim.ga.GraphOperations.extendGraph(), denoptim.fragspace.FragsCombinationIterator.FragsCombinationIterator(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.DGraph.isIsomorphicTo(), denoptim.graph.DGraph.isIsostructuralTo(), denoptim.fragspace.FragsCombinationIterator.next(), denoptim.graph.DGraph.reassignSymmetricLabels(), denoptim.graph.DGraph.removeBranchStartingAt(), denoptim.graph.DGraph.removeChainUpToBranching(), denoptim.graph.DGraph.removeSymmetryRedundance(), denoptim.graph.DGraph.renumberVerticesGetMap(), and denoptim.graph.DGraphTest.testReplaceVertex().
indexOf()
int denoptim.graph.SymmetricSet.indexOf (Integer vid)
Definition at line 98 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
remove()
void denoptim.graph.SymmetricSet.remove (Integer i)
Removes the given identifier from the list.
Parameters
i the identifiers to be removed
Definition at line 130 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.DGraph.removeSingleVertexAndWeld().
set()
void denoptim.graph.SymmetricSet.set (int index, Integer element)
Definition at line 105 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
size()
int denoptim.graph.SymmetricSet.size ()
Return the number of identifiers in this list.
Returns
the number of identifiers in this list.
Definition at line 145 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Referenced by denoptim.graph.DGraph.appendGraphOnAP(), denoptim.combinatorial.GraphBuildingTask.call(), denoptim.ga.GraphOperations.extendGraph(), denoptim.graph.Template.getSymmetricAPSets(), denoptim.graph.DGraph.insertVertex(), denoptim.graph.DGraph.removeBranchStartingAt(), denoptim.graph.DGraph.removeSingleVertexAndWeld(), denoptim.graph.DGraph.sameAs(), denoptim.graph.DGraphTest.testConvertSymmetricLabelsToSymmetricSets(), and denoptim.graph.DGraphTest.testReplaceVertex().
toString()
String denoptim.graph.SymmetricSet.toString ()
Definition at line 168 of file SymmetricSet.java.
References denoptim.graph.SymmetricSet.symIds.
Member Data Documentation
symIds
ArrayList<Integer> denoptim.graph.SymmetricSet.symIds private
Definition at line 38 of file SymmetricSet.java.
Referenced by denoptim.graph.SymmetricSet.add(), denoptim.graph.SymmetricSet.clone(), denoptim.graph.SymmetricSet.contains(), denoptim.graph.SymmetricSet.get(), denoptim.graph.SymmetricSet.getList(), denoptim.graph.SymmetricSet.indexOf(), denoptim.graph.SymmetricSet.remove(), denoptim.graph.SymmetricSet.set(), denoptim.graph.SymmetricSet.size(), denoptim.graph.SymmetricSet.SymmetricSet(), and denoptim.graph.SymmetricSet.toString().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/graph/SymmetricSet.java