DENOPTIM: denoptim.programs.fitnessevaluator.FPRunner Class Reference
denoptim.programs.fitnessevaluator.FPRunner Class Reference
Runs a fitness provider task as defined in the static parameters.
Public Member Functions
FPRunner (FRParameters settings)
Constructor.
void stopRun ()
Stops all subtasks and shutdown executor.
void run () throws Exception
Create and run the fitness task.
Package Attributes
final List< Future< Object > > futures
Storage of references to the submitted subtasks as Future
final ArrayList< FitnessTask > submitted
Storage of references to the submitted subtasks.
final ThreadPoolExecutor tpe
Asynchronous tasks manager.
Private Member Functions
void cleanup (ThreadPoolExecutor tpe, List< Future< Object > > futures, ArrayList< FitnessTask > submitted)
clean all reference to submitted tasks
Private Attributes
FRParameters settings
The parameters controlling the.
Detailed Description
Runs a fitness provider task as defined in the static parameters.
This class is meant to execute fitness provider tasks from the GUI or the CLI in a stand-alone fashion, i.e., without running GARunner or FragSpaceExplorer.
Author
Marco Foscato
Definition at line 54 of file FPRunner.java.
Constructor & Destructor Documentation
FPRunner()
denoptim.programs.fitnessevaluator.FPRunner.FPRunner (FRParameters settings)
Constructor.
Definition at line 83 of file FPRunner.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FPRunner.run(), denoptim.programs.fitnessevaluator.FPRunner.settings, denoptim.programs.fitnessevaluator.FPRunner.submitted, and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Member Function Documentation
cleanup()
void denoptim.programs.fitnessevaluator.FPRunner.cleanup (ThreadPoolExecutor tpe, List< Future< Object > > futures, ArrayList< FitnessTask > submitted) private
clean all reference to submitted tasks
Definition at line 229 of file FPRunner.java.
References denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FPRunner.submitted, and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
run()
void denoptim.programs.fitnessevaluator.FPRunner.run () throws Exception
Create and run the fitness task.
Exceptions
Exception
Definition at line 163 of file FPRunner.java.
References denoptim.logging.StaticLogger.appLogger, denoptim.constants.DENOPTIMConstants.EOL, denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FRParameters.getInputFile(), denoptim.programs.fitnessevaluator.FRParameters.getOutputFile(), denoptim.programs.RunTimeParameters.getWorkDirectory(), denoptim.io.DenoptimIO.readDENOPTIMGraphsFromFile(), denoptim.io.DenoptimIO.readSDFFile(), denoptim.io.DenoptimIO.readText(), denoptim.programs.fitnessevaluator.FPRunner.settings, denoptim.programs.fitnessevaluator.FPRunner.submitted, denoptim.programs.fitnessevaluator.FPRunner.tpe, and denoptim.io.DenoptimIO.writeData().
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FitnessRunner.runProgram().
stopRun()
void denoptim.programs.fitnessevaluator.FPRunner.stopRun ()
Stops all subtasks and shutdown executor.
Definition at line 150 of file FPRunner.java.
References denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.futures, denoptim.programs.fitnessevaluator.FPRunner.submitted, and denoptim.programs.fitnessevaluator.FPRunner.tpe.
Referenced by denoptim.programs.fitnessevaluator.FitnessRunner.handleThrowable().
Member Data Documentation
futures
final List<Future<Object> > denoptim.programs.fitnessevaluator.FPRunner.futures package
Storage of references to the submitted subtasks as Future
Definition at line 59 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), denoptim.programs.fitnessevaluator.FPRunner.run(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
settings
FRParameters denoptim.programs.fitnessevaluator.FPRunner.settings private
The parameters controlling the.
Definition at line 74 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), and denoptim.programs.fitnessevaluator.FPRunner.run().
submitted
final ArrayList<FitnessTask> denoptim.programs.fitnessevaluator.FPRunner.submitted package
Storage of references to the submitted subtasks.
Definition at line 64 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), denoptim.programs.fitnessevaluator.FPRunner.run(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
tpe
final ThreadPoolExecutor denoptim.programs.fitnessevaluator.FPRunner.tpe package
Asynchronous tasks manager.
Definition at line 69 of file FPRunner.java.
Referenced by denoptim.programs.fitnessevaluator.FPRunner.cleanup(), denoptim.programs.fitnessevaluator.FPRunner.FPRunner(), denoptim.programs.fitnessevaluator.FPRunner.run(), and denoptim.programs.fitnessevaluator.FPRunner.stopRun().
The documentation for this class was generated from the following file:
/github/workspace/src/main/java/denoptim/programs/fitnessevaluator/FPRunner.java